### ISSUE TITLE
Example notebook how to discover datasets via API request

### ISSUE THREAD

**Issue by jbusecke** [pangeo-forge/CMIP6_static_grids-feedstock#9]
From my chat with @emaroon today. It would be very helpful to have an example how to query the API for these specific grid datasets. Ill try to work on that the week after Scipy.

**Comment by cisaacstern** [comment]
Is the usefulness of this perhaps superseded by https://github.com/pangeo-forge/pangeo-forge.org/pull/93, following which, the datasets for any feedstock will be discoverable on the website?

**Comment by jbusecke** [comment]
Yes I believe it actually is. I ll close this for now.

**Comment by rabernat** [comment]
Human readable access (website) vs. machine readable access (API) are distinct use cases.

We still eventually need a STAC catalog for Pangeo Forge Cloud datasets.
